# Generated by Django 5.2.17 on 2026-08-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "shipment_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Rating",
                "verbose_name_plural": "Marketplace Ratings",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("stars__gte", 1), ("stars__lte", 5)),
                        name="stars_range_1_to_5",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("FLATBED", "Flatbed Trailer"),
                            ("TANKER", "Fuel/Liquid Tanker"),
                            ("REFRIGERATED", "Refrigerated Truck"),
                            ("CONTAINER_CARRIER", "Container Carrier"),
                            ("BOX_TRUCK", "Box Cargo Truck"),
                            ("OTHER", "Other Cargo Vehicle"),
                        ],
                        db_index=True,
                        default="FLATBED",
                        max_length=30,
                    ),
                ),
                (
                    "capacity_tonnes",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("ELECTRIC", "Electric"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="DIESEL",
                        max_length=20,
                    ),
                ),
                ("insurance_policy_number", models.CharField(max_length=100)),
                ("insurance_expiration", models.DateField(blank=True, null=True)),
                ("roadworthiness_certificate", models.CharField(max_length=100)),
                ("roadworthiness_expiration", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="accounts.transporterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fleet Vehicle",
                "verbose_name_plural": "Fleet Vehicles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transporter", "is_active"],
                        name="marketplace_transpo_c0b48c_idx",
                    ),
                    models.Index(
                        fields=["vehicle_type", "capacity_tonnes"],
                        name="marketplace_vehicle_7a0f2f_idx",
                    ),
                ],
            },
        ),
    ]
