# Generated by Django 5.2.17 on 2026-08-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("origin", models.CharField(db_index=True, max_length=255)),
                ("destination", models.CharField(db_index=True, max_length=255)),
                ("cargo_type", models.CharField(max_length=100)),
                ("weight_tonnes", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "volume_cubic_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "required_vehicle_type",
                    models.CharField(
                        choices=[
                            ("FLATBED", "Flatbed Trailer"),
                            ("TANKER", "Fuel/Liquid Tanker"),
                            ("REFRIGERATED", "Refrigerated Truck"),
                            ("CONTAINER_CARRIER", "Container Carrier"),
                            ("BOX_TRUCK", "Box Cargo Truck"),
                            ("OTHER", "Other Cargo Vehicle"),
                        ],
                        db_index=True,
                        default="FLATBED",
                        max_length=30,
                    ),
                ),
                ("pickup_date", models.DateField(db_index=True)),
                ("delivery_date", models.DateField()),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted on Spot Market"),
                            ("ASSIGNED", "Assigned to Transporter"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="POSTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_transporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_loads",
                        to="accounts.transporterprofile",
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_loads",
                        to="marketplace.vehicle",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_loads",
                        to="accounts.shipperprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo Load",
                "verbose_name_plural": "Cargo Loads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("estimated_pickup", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposed_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bids",
                        to="marketplace.vehicle",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="accounts.transporterprofile",
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="marketplace.cargoload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spot Market Bid",
                "verbose_name_plural": "Spot Market Bids",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cargoload",
            index=models.Index(
                fields=["origin", "destination"], name="marketplace_origin_3d892e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargoload",
            index=models.Index(
                fields=["status", "required_vehicle_type"],
                name="marketplace_status_9a3fa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargoload",
            index=models.Index(
                fields=["pickup_date", "status"], name="marketplace_pickup__603434_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("load", "transporter"),
                name="unique_bid_per_transporter_per_load",
            ),
        ),
    ]
