# Generated by Django 5.2.17 on 2026-08-20 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        ("marketplace", "0002_cargoload_bid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="shipment_id",
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Shipment Created"),
                            ("DRIVER_ASSIGNED", "Driver Assigned"),
                            ("AT_PICKUP", "Arrived at Pickup"),
                            ("IN_TRANSIT", "In Transit"),
                            ("AT_DESTINATION", "Arrived at Destination"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("actual_pickup_time", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="accounts.driverprofile",
                    ),
                ),
                (
                    "load",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="marketplace.cargoload",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="accounts.transporterprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="marketplace.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "heading_degrees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to="marketplace.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS Location Update",
                "verbose_name_plural": "GPS Location Updates",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="rating",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ratings",
                to="marketplace.shipment",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Shipment Created"),
                            ("DRIVER_ASSIGNED", "Driver Assigned"),
                            ("AT_PICKUP", "Arrived at Pickup"),
                            ("IN_TRANSIT", "In Transit"),
                            ("AT_DESTINATION", "Arrived at Destination"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Milestone",
                "verbose_name_plural": "Shipment Milestones",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "transporter"], name="marketplace_status_42a1f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["driver", "status"], name="marketplace_driver__cb7a6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationupdate",
            index=models.Index(
                fields=["shipment", "-timestamp"], name="marketplace_shipmen_752033_idx"
            ),
        ),
    ]
