# Generated by Django 5.2.17 on 2026-08-20 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        (
            "marketplace",
            "0003_remove_rating_shipment_id_shipment_locationupdate_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(max_length=50)),
                ("delivery_location", models.CharField(max_length=255)),
                ("delivered_at", models.DateTimeField()),
                ("signature_data", models.TextField(blank=True)),
                (
                    "cargo_condition",
                    models.CharField(
                        choices=[
                            ("GOOD_CONDITION", "Good Condition (No Damage)"),
                            ("PARTIALLY_DAMAGED", "Partially Damaged"),
                            ("SEVERELY_DAMAGED", "Severely Damaged"),
                            ("SHORTAGE_NOTED", "Quantity Shortage Noted"),
                        ],
                        default="GOOD_CONDITION",
                        max_length=30,
                    ),
                ),
                (
                    "received_weight_tonnes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("delivery_notes", models.TextField(blank=True)),
                (
                    "confirmation_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted by Driver"),
                            ("CONFIRMED", "Confirmed by Shipper"),
                            ("DISPUTED", "Disputed by Shipper"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("dispute_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proof of Delivery",
                "verbose_name_plural": "Proofs of Delivery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("WAYBILL", "Waybill / Bill of Lading"),
                            ("CUSTOMS_RELEASE", "Customs Release Certificate"),
                            ("COMMERCIAL_INVOICE", "Commercial Invoice"),
                            ("PACKING_LIST", "Packing List"),
                            ("WEIGHT_BRIDGE_TICKET", "Weighbridge Ticket"),
                            (
                                "PROOF_OF_DELIVERY_EVIDENCE",
                                "Proof of Delivery Photo/Document",
                            ),
                            ("OTHER", "Other Transport Document"),
                        ],
                        db_index=True,
                        default="WAYBILL",
                        max_length=40,
                    ),
                ),
                ("file", models.FileField(upload_to="shipment_documents/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipment Document",
                "verbose_name_plural": "Shipment Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="locationupdate",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Location Update",
                "verbose_name_plural": "Location Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="shipmentmilestone",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Shipment Milestone",
                "verbose_name_plural": "Shipment Milestones",
            },
        ),
        migrations.RemoveConstraint(
            model_name="bid",
            name="unique_bid_per_transporter_per_load",
        ),
        migrations.RemoveIndex(
            model_name="cargoload",
            name="marketplace_origin_3d892e_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargoload",
            name="marketplace_status_9a3fa0_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargoload",
            name="marketplace_pickup__603434_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="marketplace_transpo_c0b48c_idx",
        ),
        migrations.RemoveIndex(
            model_name="vehicle",
            name="marketplace_vehicle_7a0f2f_idx",
        ),
        migrations.AlterField(
            model_name="bid",
            name="estimated_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bid",
            name="estimated_pickup",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cargoload",
            name="pickup_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cargoload",
            name="required_vehicle_type",
            field=models.CharField(
                choices=[
                    ("CONTAINER_TRUCK", "Container Truck"),
                    ("FLATBED", "Flatbed Trailer"),
                    ("REFRIGERATED", "Refrigerated Truck (Reefer)"),
                    ("TANKER", "Liquid Tanker"),
                    ("BULK_CARRIER", "Dry Bulk Carrier"),
                ],
                default="FLATBED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cargoload",
            name="shipper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loads",
                to="accounts.shipperprofile",
            ),
        ),
        migrations.AlterField(
            model_name="cargoload",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("POSTED", "Posted on Spot Market"),
                    ("ASSIGNED", "Assigned to Transporter"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="POSTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locationupdate",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="locationupdate",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="locationupdate",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gps_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Shipment Initialized"),
                    ("DRIVER_ASSIGNED", "Driver Assigned"),
                    ("AT_PICKUP", "Arrived at Pickup Location"),
                    ("IN_TRANSIT", "In Transit Along Corridor"),
                    ("AT_DESTINATION", "Arrived at Destination Port/Warehouse"),
                    ("DELIVERED", "Cargo Delivered"),
                    ("CANCELLED", "Shipment Cancelled"),
                ],
                db_index=True,
                default="CREATED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentmilestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Shipment Initialized"),
                    ("DRIVER_ASSIGNED", "Driver Assigned"),
                    ("AT_PICKUP", "Arrived at Pickup Location"),
                    ("IN_TRANSIT", "In Transit Along Corridor"),
                    ("AT_DESTINATION", "Arrived at Destination Port/Warehouse"),
                    ("DELIVERED", "Cargo Delivered"),
                    ("CANCELLED", "Shipment Cancelled"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentmilestone",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="shipmentmilestone",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="insurance_policy_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="roadworthiness_certificate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("CONTAINER_TRUCK", "Container Truck"),
                    ("FLATBED", "Flatbed Trailer"),
                    ("REFRIGERATED", "Refrigerated Truck (Reefer)"),
                    ("TANKER", "Liquid Tanker"),
                    ("BULK_CARRIER", "Dry Bulk Carrier"),
                ],
                default="FLATBED",
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("load", "transporter")},
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="confirmed_by_shipper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_pods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="delivered_by_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivered_pods",
                to="accounts.driverprofile",
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="shipment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod",
                to="marketplace.shipment",
            ),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="marketplace.shipment",
            ),
        ),
        migrations.AddField(
            model_name="shipmentdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentdocument",
            index=models.Index(
                fields=["shipment", "document_type"],
                name="marketplace_shipmen_90eff9_idx",
            ),
        ),
    ]
