# Generated by Django 5.2.17 on 2026-08-21 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        ("marketplace", "0005_freightinvoice_freightsettlement_payment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationupdate",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="shipmentmilestone",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="OfflineSyncEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_event_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("device_id", models.CharField(blank=True, max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GPS_UPDATE", "GPS Location Telemetry"),
                            ("WAYPOINT_CHECKIN", "Waypoint / Check-in Milestone"),
                            ("INCIDENT_REPORT", "Driver Incident Report"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField()),
                ("client_created_at", models.DateTimeField()),
                ("server_received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synchronized Successfully"),
                            ("DUPLICATE", "Duplicate Event (Idempotent)"),
                            ("REJECTED", "Rejected (Validation / Auth Error)"),
                            (
                                "CONFLICT",
                                "Conflict (Superseded by Authoritative Event)",
                            ),
                            ("FAILED", "Processing Failed"),
                        ],
                        db_index=True,
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "server_record_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_events",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Sync Event",
                "verbose_name_plural": "Offline Sync Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverIncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("ACCIDENT", "Traffic Accident"),
                            ("CHECKPOINT_DELAY", "Customs / Police Checkpoint Delay"),
                            ("FUEL_UNAVAILABLE", "Fuel Shortage / Station Unavailable"),
                            ("ROAD_PROBLEM", "Road Damage / Blockade"),
                            ("SECURITY_INCIDENT", "Security Threat / Armed Unrest"),
                            ("VEHICLE_BREAKDOWN", "Mechanical Breakdown"),
                            ("OTHER", "Other Incident"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("reported_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="accounts.driverprofile",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "offline_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_reports",
                        to="marketplace.offlinesyncevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Incident Report",
                "verbose_name_plural": "Driver Incident Reports",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.AddIndex(
            model_name="offlinesyncevent",
            index=models.Index(
                fields=["user", "event_type"], name="marketplace_user_id_85d3e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinesyncevent",
            index=models.Index(
                fields=["shipment", "status"], name="marketplace_shipmen_076fbb_idx"
            ),
        ),
    ]
