# Generated by Django 5.2.17 on 2026-08-21 11:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0007_shipment_estimated_arrival_at_shipment_eta_basis_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("ETA_DELAY", "ETA Delay Prediction"),
                            ("SHIPMENT_RISK", "Shipment Delay Risk"),
                            ("ROUTE_RISK", "Route Risk"),
                            ("FUEL_CONSUMPTION", "Fuel Consumption Prediction"),
                            ("INCIDENT_RISK", "Incident Risk"),
                            ("OPERATIONAL_RISK", "Aggregate Operational Risk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=50)),
                (
                    "algorithm",
                    models.CharField(
                        default="Deterministic Weighted Heuristic", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("trained_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Predictive Model",
                "verbose_name_plural": "Predictive Models",
                "ordering": ["-created_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("ETA_DELAY", "ETA Delay Prediction"),
                            ("SHIPMENT_RISK", "Shipment Delay Risk"),
                            ("ROUTE_RISK", "Route Risk"),
                            ("FUEL_CONSUMPTION", "Fuel Consumption Prediction"),
                            ("INCIDENT_RISK", "Incident Risk"),
                            ("OPERATIONAL_RISK", "Aggregate Operational Risk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prediction_value", models.JSONField(default=dict)),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.80"), max_digits=4
                    ),
                ),
                (
                    "prediction_horizon_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("24.00"), max_digits=6
                    ),
                ),
                ("input_features", models.JSONField(default=dict)),
                ("explanation", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="marketplace.route",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "prediction_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="marketplace.predictivemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction Record",
                "verbose_name_plural": "Prediction Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "prediction_type", "-created_at"],
                        name="marketplace_shipmen_6bad67_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="marketplace_risk_le_9b8b33_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="marketplace_created_ab1728_idx"
                    ),
                ],
            },
        ),
    ]
