# Generated by Django 5.2.17 on 2026-08-22 11:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_predictivemodel_predictionrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingMarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_region", models.CharField(db_index=True, max_length=100)),
                ("destination_region", models.CharField(db_index=True, max_length=100)),
                ("active_load_count", models.IntegerField(default=0)),
                ("active_bid_count", models.IntegerField(default=0)),
                ("available_transporter_count", models.IntegerField(default=0)),
                (
                    "average_historical_price_etb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "average_price_per_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "demand_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=5
                    ),
                ),
                (
                    "supply_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=5
                    ),
                ),
                (
                    "market_pressure",
                    models.CharField(
                        choices=[
                            (
                                "LOW",
                                "Low Demand Pressure (Abundant Transporters / Low Load Volume)",
                            ),
                            ("NORMAL", "Normal Balanced Market Conditions"),
                            (
                                "HIGH",
                                "High Demand Pressure (High Load Volume / Transporter Scarcity)",
                            ),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pricing Market Snapshot",
                "verbose_name_plural": "Pricing Market Snapshots",
                "ordering": ["-snapshot_at"],
                "indexes": [
                    models.Index(
                        fields=["origin_region", "destination_region", "-snapshot_at"],
                        name="marketplace_origin__3c4317_idx",
                    ),
                    models.Index(
                        fields=["snapshot_at"], name="marketplace_snapsho_cbe0b3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PricingStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "base_rate_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                (
                    "minimum_rate_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("35.00"), max_digits=10
                    ),
                ),
                (
                    "maximum_rate_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("120.00"), max_digits=10
                    ),
                ),
                (
                    "fuel_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "distance_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "risk_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "incident_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "route_deviation_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "market_demand_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                (
                    "market_supply_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Strategy",
                "verbose_name_plural": "Pricing Strategies",
                "ordering": ["-is_active", "name", "version"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="marketplace_is_acti_0c77c9_idx"
                    ),
                    models.Index(
                        fields=["name", "version"], name="marketplace_name_939ab0_idx"
                    ),
                ],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="PriceRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "minimum_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "maximum_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "base_price_etb",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "distance_adjustment_etb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "fuel_adjustment_etb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "risk_adjustment_etb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "market_adjustment_etb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "pricing_confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.85"), max_digits=4
                    ),
                ),
                (
                    "market_pressure",
                    models.CharField(
                        choices=[
                            (
                                "LOW",
                                "Low Demand Pressure (Abundant Transporters / Low Load Volume)",
                            ),
                            ("NORMAL", "Normal Balanced Market Conditions"),
                            (
                                "HIGH",
                                "High Demand Pressure (High Load Volume / Transporter Scarcity)",
                            ),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=list,
                        help_text="Structured list of pricing breakdown factors with ETB impact and description.",
                    ),
                ),
                (
                    "calculation_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Audit snapshot of exact input features (distance, fuel cost, risk score, market pressure).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_recommendations",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "pricing_strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="marketplace.pricingstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Recommendation",
                "verbose_name_plural": "Price Recommendations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shipment", "-created_at"],
                        name="marketplace_shipmen_c92447_idx",
                    ),
                    models.Index(
                        fields=["market_pressure"],
                        name="marketplace_market__281b5a_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="marketplace_risk_le_379751_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="marketplace_created_2db0d0_idx"
                    ),
                ],
            },
        ),
    ]
