# Generated by Django 5.2.17 on 2026-08-22 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_pricingmarketsnapshot_pricingstrategy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique descriptive name for the rule.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("HIGH_OPERATIONAL_RISK", "High Operational Risk"),
                            ("ROUTE_DEVIATION", "Route Deviation Detected"),
                            ("HIGH_ETA_DELAY", "High ETA Delay Predicted"),
                            ("INCIDENT_REPORTED", "Driver Incident Reported"),
                            ("HIGH_FUEL_RISK", "High Fuel Consumption/Cost"),
                            ("HIGH_MARKET_PRESSURE", "High Corridor Market Pressure"),
                            ("STALE_GPS_DATA", "Stale GPS Telemetry"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of rule conditions.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Configurable rule parameters and threshold metrics.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("REVIEW_SHIPMENT", "Review Shipment Operations"),
                            ("REVIEW_ROUTE", "Review Planned Route"),
                            ("RECALCULATE_ROUTE", "Recalculate Route"),
                            ("CONTACT_DRIVER", "Contact Assigned Driver"),
                            ("REVIEW_INCIDENT", "Review Reported Incident"),
                            ("REVIEW_PRICING", "Review Freight Market Pricing"),
                            ("ESCALATE_TO_ADMIN", "Escalate to Platform Admin"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("recommended_action", models.CharField(max_length=200)),
                (
                    "context_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Immutable operational evidence snapshot at evaluation time.",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided when recommendation is rejected.",
                    ),
                ),
                (
                    "execution_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Audit details produced upon successful execution.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_recommendations",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="marketplace.automationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Recommendation",
                "verbose_name_plural": "Automation Recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("result", models.JSONField(default=dict)),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_automation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="marketplace.automationrecommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Execution",
                "verbose_name_plural": "Automation Executions",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["recommendation", "-executed_at"],
                        name="marketplace_recomme_7d498e_idx",
                    ),
                    models.Index(
                        fields=["executed_at"], name="marketplace_execute_6da291_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="automationrecommendation",
            index=models.Index(
                fields=["shipment", "status"], name="marketplace_shipmen_7b7a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrecommendation",
            index=models.Index(
                fields=["shipment", "rule", "status"],
                name="marketplace_shipmen_58756b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrecommendation",
            index=models.Index(fields=["status"], name="marketplace_status_1478ac_idx"),
        ),
        migrations.AddIndex(
            model_name="automationrecommendation",
            index=models.Index(
                fields=["created_at"], name="marketplace_created_155a8b_idx"
            ),
        ),
    ]
