# Generated by Django 5.2.17 on 2026-08-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_automationrule_automationrecommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_alerts_enabled", models.BooleanField(default=True)),
                ("eta_alerts_enabled", models.BooleanField(default=True)),
                ("risk_alerts_enabled", models.BooleanField(default=True)),
                ("incident_alerts_enabled", models.BooleanField(default=True)),
                ("fuel_alerts_enabled", models.BooleanField(default=True)),
                ("market_alerts_enabled", models.BooleanField(default=True)),
                ("automation_alerts_enabled", models.BooleanField(default=True)),
                ("shipment_updates_enabled", models.BooleanField(default=True)),
                ("system_alerts_enabled", models.BooleanField(default=True)),
                ("critical_alerts_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="OperationalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ROUTE_DEVIATION", "Route Deviation Detected"),
                            ("ETA_DELAY", "ETA Arrival Delay Predicted"),
                            ("HIGH_OPERATIONAL_RISK", "High Operational Risk Level"),
                            ("INCIDENT_REPORTED", "Driver Incident Reported"),
                            ("FUEL_RISK", "High Fuel Consumption Risk"),
                            ("HIGH_MARKET_PRESSURE", "High Corridor Market Pressure"),
                            ("STALE_GPS", "Stale GPS Telemetry Ping"),
                            (
                                "AUTOMATION_RECOMMENDATION",
                                "Workflow Recommendation Created",
                            ),
                            (
                                "AUTOMATION_APPROVAL_REQUIRED",
                                "Workflow Recommendation Requires Approval",
                            ),
                            ("AUTOMATION_EXECUTED", "Workflow Recommendation Executed"),
                            ("SHIPMENT_STATUS_CHANGED", "Shipment Status Transition"),
                            ("PAYMENT_EVENT", "Freight Settlement / Payment Event"),
                            ("SYSTEM_ALERT", "System Operational Alert"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="SYSTEM", max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_operational_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_events",
                        to="marketplace.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Event",
                "verbose_name_plural": "Operational Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL_ALERT", "Operational Alert"),
                            ("SHIPMENT_UPDATE", "Shipment Update"),
                            ("ROUTE_ALERT", "Route Corridor Alert"),
                            ("ETA_ALERT", "ETA Delay Alert"),
                            ("RISK_ALERT", "Risk Level Alert"),
                            ("INCIDENT_ALERT", "Driver Incident Alert"),
                            ("FUEL_ALERT", "Fuel Consumption Alert"),
                            ("MARKET_ALERT", "Corridor Market Alert"),
                            ("AUTOMATION_ALERT", "Workflow Automation Alert"),
                            ("SYSTEM_ALERT", "System Operational Alert"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="marketplace.operationalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operationalevent",
            index=models.Index(
                fields=["shipment", "-created_at"],
                name="marketplace_shipmen_858c02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationalevent",
            index=models.Index(
                fields=["event_type", "severity"], name="marketplace_event_t_9e903e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationalevent",
            index=models.Index(
                fields=["created_at"], name="marketplace_created_ab2057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operationalevent",
            index=models.Index(
                fields=["idempotency_key"], name="marketplace_idempot_f7b1c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="marketplace_recipie_86928c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"],
                name="marketplace_recipie_42ac4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["shipment", "-created_at"],
                name="marketplace_shipmen_30f570_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority"], name="marketplace_priorit_06a11f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("event", "recipient"),
                name="unique_event_recipient_notification",
            ),
        ),
    ]
