# Generated by Django 5.2.17 on 2026-08-22 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0011_notificationpreference_operationalevent_notification_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("ERP", "Enterprise Resource Planning"),
                            ("ACCOUNTING", "Accounting & Financial System"),
                            ("LOGISTICS", "Logistics Platform"),
                            ("TRACKING", "Telematics & Tracking Service"),
                            ("ANALYTICS", "Enterprise Analytics System"),
                            ("CUSTOM", "Custom Webhook Integration"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DISABLED", "Disabled by System"),
                            ("ERROR", "Error / Connection Failed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("api_key_reference", models.CharField(blank=True, max_length=255)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "External Integration",
                "verbose_name_plural": "External Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                (
                    "event_types",
                    models.JSONField(
                        default=list, help_text="List of subscribed event type strings"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("secret", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="marketplace.externalintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("external_event_id", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("signature_valid", models.BooleanField(default=False)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed Successfully"),
                            ("FAILED", "Processing Failed"),
                            ("REJECTED", "Signature / Format Rejected"),
                            ("DUPLICATE", "Duplicate Event Ignored"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_events",
                        to="marketplace.externalintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbound Webhook Event",
                "verbose_name_plural": "Inbound Webhook Events",
                "ordering": ["-received_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("integration", "external_event_id"),
                        name="unique_integration_external_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Delivery"),
                            ("PROCESSING", "Processing HTTP Request"),
                            ("DELIVERED", "Delivered Successfully"),
                            ("FAILED", "Delivery Failed"),
                            ("RETRYING", "Retrying Delivery"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "response_body",
                    models.TextField(
                        blank=True, help_text="Truncated response body (max 2000 chars)"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="marketplace.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook_endpoint", "status"],
                        name="marketplace_webhook_8521d3_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="marketplace_status_4d6aea_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("webhook_endpoint", "idempotency_key"),
                        name="unique_endpoint_idempotency_delivery",
                    )
                ],
            },
        ),
    ]
