# Generated by Django 5.2.17 on 2026-08-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_externalintegration_webhookendpoint_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("BRUTE_FORCE", "Brute Force Attack"),
                            ("ACCOUNT_COMPROMISE", "Account Compromise Suspected"),
                            ("PRIVILEGE_ESCALATION", "Privilege Escalation Attempt"),
                            ("SUSPICIOUS_API_ACCESS", "Suspicious API Access"),
                            ("SUSPICIOUS_LOGIN", "Suspicious Login Activity"),
                            ("WEBHOOK_ATTACK", "Webhook Tampering / Signature Failure"),
                            (
                                "INTEGRATION_SECURITY_FAILURE",
                                "Integration Authentication Failure",
                            ),
                            (
                                "UNAUTHORIZED_DATA_ACCESS",
                                "Unauthorized Data Access Attempt",
                            ),
                            ("POLICY_VIOLATION", "Security Policy Violation"),
                            (
                                "AUDIT_INTEGRITY_FAILURE",
                                "Audit Chain Hash Integrity Violation",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("CONTAINED", "Contained"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed / False Positive"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detected_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("policy_type", models.CharField(db_index=True, max_length=100)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("threshold", models.PositiveIntegerField(default=5)),
                ("window_seconds", models.PositiveIntegerField(default=600)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        default="HIGH",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_security_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_security_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Policy",
                "verbose_name_plural": "Security Policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Successful Login"),
                            ("LOGIN_FAILURE", "Failed Login Attempt"),
                            ("LOGOUT", "User Logout"),
                            ("TOKEN_REFRESH", "JWT Token Refresh"),
                            ("TOKEN_REVOKED", "JWT Token Revoked"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("USER_CREATED", "User Created"),
                            ("USER_UPDATED", "User Profile Updated"),
                            ("USER_DEACTIVATED", "User Deactivated"),
                            ("USER_REACTIVATED", "User Reactivated"),
                            ("ROLE_CHANGED", "User Role Changed"),
                            ("PERMISSION_GRANTED", "Permission Granted"),
                            ("PERMISSION_REVOKED", "Permission Revoked"),
                            ("SENSITIVE_DATA_ACCESSED", "Sensitive Data Accessed"),
                            ("ADMIN_ACTION", "Administrative Action Performed"),
                            ("API_ACCESS_DENIED", "API Access Denied (401/403)"),
                            (
                                "WEBHOOK_SECURITY_FAILURE",
                                "Webhook Signature/Security Failure",
                            ),
                            (
                                "INTEGRATION_SECURITY_FAILURE",
                                "Integration Security Failure",
                            ),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity Detected"),
                            ("SECURITY_POLICY_VIOLATION", "Security Policy Violation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("LOW", "Low Severity"),
                            ("MEDIUM", "Medium Severity"),
                            ("HIGH", "High Severity"),
                            ("CRITICAL", "Critical Severity"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=50)),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_object_id", models.CharField(blank=True, max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                ("event_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Audit Event",
                "verbose_name_plural": "Security Audit Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "event_type"],
                        name="marketplace_created_404ea5_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="marketplace_actor_i_8e018c_idx",
                    ),
                    models.Index(
                        fields=["target_user", "created_at"],
                        name="marketplace_target__225c9a_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="marketplace_severit_78d0c5_idx",
                    ),
                ],
            },
        ),
    ]
