# Generated by Django 5.2.17 on 2026-08-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_securityincident_securitypolicy_securityauditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, default="MockAIProvider", max_length=100
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        default="tradeflow-decision-support-v1",
                        max_length=100,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("temperature", models.FloatField(default=0.2)),
                ("max_tokens", models.PositiveIntegerField(default=1024)),
                ("timeout_seconds", models.PositiveIntegerField(default=10)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model Configuration",
                "verbose_name_plural": "AI Model Configurations",
                "ordering": ["-is_active", "provider", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("version", models.CharField(default="v1.0", max_length=50)),
                ("task_type", models.CharField(db_index=True, max_length=100)),
                ("template", models.TextField()),
                ("system_instruction", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Prompt Version",
                "verbose_name_plural": "AI Prompt Versions",
                "ordering": ["name", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_prompt_name_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("recommendation", models.TextField()),
                ("rationale", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("confidence_score", models.FloatField(default=0.9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Human Review"),
                            ("ACCEPTED", "Accepted by Human"),
                            ("REJECTED", "Rejected by Human"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(default="MEDIUM", max_length=20)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Recommendation",
                "verbose_name_plural": "AI Recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=255)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("model", models.CharField(db_index=True, max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Record",
                "verbose_name_plural": "AI Usage Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=255)),
                ("task_type", models.CharField(db_index=True, max_length=100)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(default="v1.0", max_length=50)),
                ("input_reference", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Generation Request",
                "verbose_name_plural": "AI Generation Requests",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["started_at", "task_type"],
                        name="marketplace_started_832ee3_idx",
                    ),
                    models.Index(
                        fields=["user", "started_at"],
                        name="marketplace_user_id_d47b9c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("SHIPMENT_SUMMARY", "Shipment Executive Summary"),
                            ("RISK_EXPLANATION", "Shipment Risk Explanation"),
                            ("INCIDENT_ANALYSIS", "Incident Analysis"),
                            ("ROUTE_ANALYSIS", "Route & Telemetry Analysis"),
                            ("ETA_EXPLANATION", "ETA Variance Explanation"),
                            ("MARKET_ANALYSIS", "Market & Demand Analysis"),
                            ("PRICING_EXPLANATION", "Freight Pricing Explanation"),
                            ("OPERATIONAL_ANOMALY", "Operational Anomaly Explanation"),
                            ("EXECUTIVE_SUMMARY", "Executive Operations Summary"),
                            (
                                "GENERAL_OPERATIONAL_INSIGHT",
                                "General Operational Insight",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("detailed_analysis", models.TextField(blank=True)),
                ("confidence_score", models.FloatField(default=0.95)),
                (
                    "severity",
                    models.CharField(db_index=True, default="INFO", max_length=20),
                ),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="marketplace.shipment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Insight",
                "verbose_name_plural": "AI Insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "insight_type", "created_at"],
                        name="marketplace_user_id_f9a26a_idx",
                    ),
                    models.Index(
                        fields=["shipment", "insight_type"],
                        name="marketplace_shipmen_cb75dc_idx",
                    ),
                ],
            },
        ),
    ]
