from django.urls import path
from apps.marketplace.views import (
    TransporterListView,
    TransporterMeProfileView,
    TransporterVehicleListCreateView,
    TransporterVehicleDetailView,
    TransporterVerificationView,
    TransporterVerificationAuditListView,
    LoadListCreateView,
    LoadDetailView,
    LoadCancelView,
    LoadBidsListCreateView,
    BidAcceptView,
    BidWithdrawView,
    TransporterMyBidsView,
    ShipmentListView,
    ShipmentDetailView,
    ShipmentAssignDriverView,
    ShipmentStatusUpdateView,
    ShipmentLocationView,
    ShipmentTrackingHistoryView,
    ShipmentDocumentListUploadView,
    DocumentDetailView,
    DocumentDownloadView,
    ShipmentPODView,
    PODConfirmView,
    PODDisputeView,
    PaymentInitiateView,
    PaymentListView,
    PaymentDetailView,
    PaymentVerifyView,
    PaymentReconcileView,
    ShipmentPaymentsView,
    FreightInvoiceListView,
    FreightInvoiceDetailView,
    FreightSettlementCreateView,
    FreightSettlementListView,
    FreightSettlementDetailView,
    FreightSettlementDisputeView,
    TransporterPayoutListView,
    TransporterPayoutDetailView,
    TransporterPayoutProcessView,
    RatingListCreateView,
)

urlpatterns = [
    # Transporters & Fleet
    path('transporters/', TransporterListView.as_view(), name='transporter-list'),
    path('transporters/me/', TransporterMeProfileView.as_view(), name='transporter-me'),
    path('transporters/me/vehicles/', TransporterVehicleListCreateView.as_view(), name='transporter-vehicle-list-create'),
    path('transporters/me/vehicles/<int:pk>/', TransporterVehicleDetailView.as_view(), name='transporter-vehicle-detail'),
    path('transporters/<int:pk>/verification/', TransporterVerificationView.as_view(), name='transporter-verification'),
    path('transporters/<int:pk>/verification/history/', TransporterVerificationAuditListView.as_view(), name='transporter-verification-audit'),

    # Cargo Loads & Spot Market Bids
    path('loads/', LoadListCreateView.as_view(), name='load-list-create'),
    path('loads/<int:pk>/', LoadDetailView.as_view(), name='load-detail'),
    path('loads/<int:pk>/cancel/', LoadCancelView.as_view(), name='load-cancel'),
    path('loads/<int:pk>/bids/', LoadBidsListCreateView.as_view(), name='load-bids-list-create'),
    path('bids/<int:pk>/accept/', BidAcceptView.as_view(), name='bid-accept'),
    path('bids/<int:pk>/withdraw/', BidWithdrawView.as_view(), name='bid-withdraw'),
    path('bids/me/', TransporterMyBidsView.as_view(), name='transporter-bids-me'),

    # Shipments & Real-Time Tracking
    path('shipments/', ShipmentListView.as_view(), name='shipment-list'),
    path('shipments/<int:pk>/', ShipmentDetailView.as_view(), name='shipment-detail'),
    path('shipments/<int:pk>/assign-driver/', ShipmentAssignDriverView.as_view(), name='shipment-assign-driver'),
    path('shipments/<int:pk>/status/', ShipmentStatusUpdateView.as_view(), name='shipment-status-update'),
    path('shipments/<int:pk>/location/', ShipmentLocationView.as_view(), name='shipment-location'),
    path('shipments/<int:pk>/tracking/', ShipmentTrackingHistoryView.as_view(), name='shipment-tracking-history'),

    # Document Management & Digital Proof of Delivery (e-POD)
    path('shipments/<int:pk>/documents/', ShipmentDocumentListUploadView.as_view(), name='shipment-document-list-upload'),
    path('documents/<int:pk>/', DocumentDetailView.as_view(), name='document-detail'),
    path('documents/<int:pk>/download/', DocumentDownloadView.as_view(), name='document-download'),
    path('shipments/<int:pk>/pod/', ShipmentPODView.as_view(), name='shipment-pod'),
    path('pod/<int:pk>/confirm/', PODConfirmView.as_view(), name='pod-confirm'),
    path('pod/<int:pk>/dispute/', PODDisputeView.as_view(), name='pod-dispute'),

    # Phase 8: Payments & Freight Settlement (FR-10)
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('payments/initiate/', PaymentInitiateView.as_view(), name='payment-initiate'),
    path('payments/<int:pk>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('payments/<int:pk>/verify/', PaymentVerifyView.as_view(), name='payment-verify'),
    path('payments/<int:pk>/reconcile/', PaymentReconcileView.as_view(), name='payment-reconcile'),
    path('shipments/<int:pk>/payments/', ShipmentPaymentsView.as_view(), name='shipment-payments'),
    path('invoices/', FreightInvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<int:pk>/', FreightInvoiceDetailView.as_view(), name='invoice-detail'),
    path('settlements/', FreightSettlementListView.as_view(), name='settlement-list'),
    path('settlements/create/', FreightSettlementCreateView.as_view(), name='settlement-create'),
    path('settlements/<int:pk>/', FreightSettlementDetailView.as_view(), name='settlement-detail'),
    path('settlements/<int:pk>/dispute/', FreightSettlementDisputeView.as_view(), name='settlement-dispute'),
    path('payouts/', TransporterPayoutListView.as_view(), name='payout-list'),
    path('payouts/<int:pk>/', TransporterPayoutDetailView.as_view(), name='payout-detail'),
    path('payouts/<int:pk>/process/', TransporterPayoutProcessView.as_view(), name='payout-process'),

    # Ratings
    path('ratings/', RatingListCreateView.as_view(), name='rating-list-create'),
]
