from django.urls import path
from apps.marketplace.views import (
    TransporterListView,
    TransporterMeProfileView,
    TransporterVehicleListCreateView,
    TransporterVehicleDetailView,
    TransporterVerificationView,
    TransporterVerificationAuditListView,
    LoadListCreateView,
    LoadDetailView,
    LoadCancelView,
    LoadBidsListCreateView,
    BidAcceptView,
    BidWithdrawView,
    TransporterMyBidsView,
    ShipmentListView,
    ShipmentDetailView,
    ShipmentAssignDriverView,
    ShipmentStatusUpdateView,
    ShipmentLocationView,
    ShipmentTrackingHistoryView,
    ShipmentETAView,
    ShipmentDocumentListUploadView,
    DocumentDetailView,
    DocumentDownloadView,
    ShipmentPODView,
    PODConfirmView,
    PODDisputeView,
    PaymentInitiateView,
    PaymentListView,
    PaymentDetailView,
    PaymentVerifyView,
    PaymentReconcileView,
    ShipmentPaymentsView,
    FreightInvoiceListView,
    FreightInvoiceDetailView,
    FreightSettlementCreateView,
    FreightSettlementListView,
    FreightSettlementDetailView,
    FreightSettlementDisputeView,
    TransporterPayoutListView,
    TransporterPayoutDetailView,
    TransporterPayoutProcessView,
    RatingListCreateView,
    OfflineSyncBatchView,
    DriverIncidentReportListView,
    ShipmentRouteCreateListAPIView,
    ShipmentRouteRecalculateAPIView,
    ShipmentRouteAnalyticsAPIView,
    ShipmentETAAPIView,
    ShipmentFuelAnalyticsAPIView,
    ShipmentRouteDeviationAPIView,
    ShipmentPredictiveDashboardAPIView,
    ShipmentETAPredictionAPIView,
    ShipmentRiskPredictionAPIView,
    ShipmentRouteRiskPredictionAPIView,
    ShipmentFuelPredictionAPIView,
    ShipmentIncidentRiskPredictionAPIView,
    ShipmentPredictionHistoryAPIView,
    PriceRecommendationAPIView,
    PriceRecommendationHistoryAPIView,
    MarketIntelligenceAPIView,
    PricingStrategyListAPIView,
    EvaluateShipmentAutomationAPIView,
    ShipmentAutomationListAPIView,
    ShipmentAutomationHistoryAPIView,
    AutomationRecommendationDetailAPIView,
    AutomationRecommendationApproveAPIView,
    AutomationRecommendationRejectAPIView,
    AutomationRecommendationExecuteAPIView,
    AutomationRuleListAPIView,
    NotificationListAPIView,
    NotificationUnreadCountAPIView,
    NotificationDetailAPIView,
    NotificationReadAPIView,
    NotificationReadAllAPIView,
    NotificationAcknowledgeAPIView,
    ShipmentEventListAPIView,
    EventDetailAPIView,
    NotificationPreferenceAPIView,
    OperationalDashboardAPIView,
    OperationalHealthAPIView,
    OperationalAttentionQueueAPIView,
    OperationalAlertIntelligenceAPIView,
    OperationalAlertTrendsAPIView,
    OperationalRiskDistributionAPIView,
    OperationalIncidentIntelligenceAPIView,
    OperationalTelemetryIntelligenceAPIView,
    OperationalMarketIntelligenceAPIView,
    OperationalAutomationIntelligenceAPIView,
    ShipmentOperationalSummaryAPIView,
    HealthCheckAPIView,
    ReadinessCheckAPIView,
    SystemMetricsAPIView,
    SystemStatusAPIView,
    AnalyticsDashboardAPIView,
    AnalyticsShipmentsAPIView,
    AnalyticsDeliveryPerformanceAPIView,
    AnalyticsFinancialAPIView,
    AnalyticsMarketAPIView,
    AnalyticsRiskAPIView,
    AnalyticsIncidentAPIView,
    AnalyticsRouteAPIView,
    AnalyticsAutomationAPIView,
    AnalyticsEventAPIView,
    AnalyticsCorridorAPIView,
    AnalyticsTopPerformersAPIView,
    AnalyticsTrendsAPIView,
    AnalyticsReportsAPIView,
    ExternalIntegrationListCreateAPIView,
    ExternalIntegrationDetailAPIView,
    ExternalIntegrationActivateAPIView,
    ExternalIntegrationDeactivateAPIView,
    ExternalIntegrationHealthAPIView,
    WebhookEndpointListCreateAPIView,
    WebhookEndpointDetailAPIView,
    WebhookEndpointActivateAPIView,
    WebhookEndpointDeactivateAPIView,
    WebhookEndpointRotateSecretAPIView,
    IntegrationDeliveriesListAPIView,
    WebhookEndpointDeliveriesListAPIView,
    WebhookDeliveryDetailAPIView,
    WebhookDeliveryRetryAPIView,
    IntegrationEventPublishAPIView,
    InboundWebhookReceiverAPIView,
    SecurityOverviewAPIView,
    SecurityAuditEventListAPIView,
    SecurityAuditEventDetailAPIView,
    SecurityIncidentListAPIView,
    SecurityIncidentDetailAPIView,
    SecurityIncidentAssignAPIView,
    SecurityIncidentResolveAPIView,
    SecurityIncidentDismissAPIView,
    UserSecurityHistoryAPIView,
    SecurityPolicyListCreateAPIView,
    SecurityPolicyDetailAPIView,
    AuditIntegrityCheckAPIView,
    SecurityComplianceReportAPIView,
)






urlpatterns = [
    # Transporters & Fleet
    path('transporters/', TransporterListView.as_view(), name='transporter-list'),
    path('transporters/me/', TransporterMeProfileView.as_view(), name='transporter-me'),
    path('transporters/me/vehicles/', TransporterVehicleListCreateView.as_view(), name='transporter-vehicle-list-create'),
    path('transporters/me/vehicles/<int:pk>/', TransporterVehicleDetailView.as_view(), name='transporter-vehicle-detail'),
    path('transporters/<int:pk>/verification/', TransporterVerificationView.as_view(), name='transporter-verification'),
    path('transporters/<int:pk>/verification/history/', TransporterVerificationAuditListView.as_view(), name='transporter-verification-audit'),

    # Cargo Loads & Spot Market Bids
    path('loads/', LoadListCreateView.as_view(), name='load-list-create'),
    path('loads/<int:pk>/', LoadDetailView.as_view(), name='load-detail'),
    path('loads/<int:pk>/cancel/', LoadCancelView.as_view(), name='load-cancel'),
    path('loads/<int:pk>/bids/', LoadBidsListCreateView.as_view(), name='load-bids-list-create'),
    path('bids/<int:pk>/accept/', BidAcceptView.as_view(), name='bid-accept'),
    path('bids/<int:pk>/withdraw/', BidWithdrawView.as_view(), name='bid-withdraw'),
    path('bids/me/', TransporterMyBidsView.as_view(), name='transporter-bids-me'),

    # Shipments & Real-Time Tracking
    path('shipments/', ShipmentListView.as_view(), name='shipment-list'),
    path('shipments/<int:pk>/', ShipmentDetailView.as_view(), name='shipment-detail'),
    path('shipments/<int:pk>/assign-driver/', ShipmentAssignDriverView.as_view(), name='shipment-assign-driver'),
    path('shipments/<int:pk>/status/', ShipmentStatusUpdateView.as_view(), name='shipment-status-update'),
    path('shipments/<int:pk>/location/', ShipmentLocationView.as_view(), name='shipment-location'),
    path('shipments/<int:pk>/tracking/', ShipmentTrackingHistoryView.as_view(), name='shipment-tracking-history'),

    # Document Management & Digital Proof of Delivery (e-POD)
    path('shipments/<int:pk>/documents/', ShipmentDocumentListUploadView.as_view(), name='shipment-document-list-upload'),
    path('documents/<int:pk>/', DocumentDetailView.as_view(), name='document-detail'),
    path('documents/<int:pk>/download/', DocumentDownloadView.as_view(), name='document-download'),
    path('shipments/<int:pk>/pod/', ShipmentPODView.as_view(), name='shipment-pod'),
    path('pod/<int:pk>/confirm/', PODConfirmView.as_view(), name='pod-confirm'),
    path('pod/<int:pk>/dispute/', PODDisputeView.as_view(), name='pod-dispute'),

    # Payments & Freight Settlement Engine
    path('payments/initiate/', PaymentInitiateView.as_view(), name='payment-initiate'),
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('payments/<int:pk>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('payments/<int:pk>/verify/', PaymentVerifyView.as_view(), name='payment-verify'),
    path('payments/<int:pk>/reconcile/', PaymentReconcileView.as_view(), name='payment-reconcile'),
    path('shipments/<int:shipment_id>/payments/', ShipmentPaymentsView.as_view(), name='shipment-payments'),
    path('invoices/', FreightInvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<int:pk>/', FreightInvoiceDetailView.as_view(), name='invoice-detail'),
    path('settlements/', FreightSettlementListView.as_view(), name='settlement-list'),
    path('settlements/<int:pk>/', FreightSettlementDetailView.as_view(), name='settlement-detail'),
    path('settlements/create/', FreightSettlementCreateView.as_view(), name='settlement-create'),
    path('settlements/<int:pk>/dispute/', FreightSettlementDisputeView.as_view(), name='settlement-dispute'),
    path('payouts/', TransporterPayoutListView.as_view(), name='payout-list'),
    path('payouts/<int:pk>/', TransporterPayoutDetailView.as_view(), name='payout-detail'),
    path('payouts/<int:pk>/process/', TransporterPayoutProcessView.as_view(), name='payout-process'),

    # Phase 9: Offline-First Synchronization & Incidents (SRS 2.4, 4.1, 5.2)
    path('sync/events/', OfflineSyncBatchView.as_view(), name='sync-events'),
    path('shipments/<int:shipment_id>/incidents/', DriverIncidentReportListView.as_view(), name='shipment-incidents'),

    # Phase 10: Route Optimization, ETA & Fuel Analytics
    path('shipments/<int:shipment_id>/route/', ShipmentRouteCreateListAPIView.as_view(), name='shipment-route'),
    path('shipments/<int:shipment_id>/route/recalculate/', ShipmentRouteRecalculateAPIView.as_view(), name='shipment-route-recalculate'),
    path('shipments/<int:shipment_id>/route/analytics/', ShipmentRouteAnalyticsAPIView.as_view(), name='shipment-route-analytics'),
    path('shipments/<int:shipment_id>/eta/', ShipmentETAAPIView.as_view(), name='shipment-eta'),
    path('shipments/<int:shipment_id>/fuel/', ShipmentFuelAnalyticsAPIView.as_view(), name='shipment-fuel'),
    path('shipments/<int:shipment_id>/deviation/', ShipmentRouteDeviationAPIView.as_view(), name='shipment-deviation'),

    # Phase 11: AI Predictive Logistics & Risk Intelligence
    path('shipments/<int:shipment_id>/predictions/', ShipmentPredictiveDashboardAPIView.as_view(), name='shipment-predictive-dashboard'),
    path('shipments/<int:shipment_id>/predictions/eta/', ShipmentETAPredictionAPIView.as_view(), name='shipment-prediction-eta'),
    path('shipments/<int:shipment_id>/predictions/risk/', ShipmentRiskPredictionAPIView.as_view(), name='shipment-prediction-risk'),
    path('shipments/<int:shipment_id>/predictions/route-risk/', ShipmentRouteRiskPredictionAPIView.as_view(), name='shipment-prediction-route-risk'),
    path('shipments/<int:shipment_id>/predictions/fuel/', ShipmentFuelPredictionAPIView.as_view(), name='shipment-prediction-fuel'),
    path('shipments/<int:shipment_id>/predictions/incident-risk/', ShipmentIncidentRiskPredictionAPIView.as_view(), name='shipment-prediction-incident-risk'),
    path('shipments/<int:shipment_id>/predictions/history/', ShipmentPredictionHistoryAPIView.as_view(), name='shipment-prediction-history'),

    # Phase 12: Dynamic Pricing & Freight Market Intelligence
    path('shipments/<int:shipment_id>/pricing/', PriceRecommendationAPIView.as_view(), name='shipment-pricing-recommendation'),
    path('shipments/<int:shipment_id>/pricing/history/', PriceRecommendationHistoryAPIView.as_view(), name='shipment-pricing-history'),
    path('shipments/<int:shipment_id>/pricing/market/', MarketIntelligenceAPIView.as_view(), name='shipment-pricing-market'),
    path('pricing/strategies/', PricingStrategyListAPIView.as_view(), name='pricing-strategy-list'),

    # Phase 13: Automated Workflow & Smart Operations
    path('shipments/<int:shipment_id>/automation/evaluate/', EvaluateShipmentAutomationAPIView.as_view(), name='shipment-automation-evaluate'),
    path('shipments/<int:shipment_id>/automation/', ShipmentAutomationListAPIView.as_view(), name='shipment-automation-list'),
    path('shipments/<int:shipment_id>/automation/history/', ShipmentAutomationHistoryAPIView.as_view(), name='shipment-automation-history'),
    path('automation/recommendations/<int:pk>/', AutomationRecommendationDetailAPIView.as_view(), name='automation-recommendation-detail'),
    path('automation/recommendations/<int:pk>/approve/', AutomationRecommendationApproveAPIView.as_view(), name='automation-recommendation-approve'),
    path('automation/recommendations/<int:pk>/reject/', AutomationRecommendationRejectAPIView.as_view(), name='automation-recommendation-reject'),
    path('automation/recommendations/<int:pk>/execute/', AutomationRecommendationExecuteAPIView.as_view(), name='automation-recommendation-execute'),
    path('automation/rules/', AutomationRuleListAPIView.as_view(), name='automation-rule-list'),

    # Phase 14: Real-Time Operations, Notifications & Event Intelligence
    path('notifications/', NotificationListAPIView.as_view(), name='notification-list'),
    path('notifications/unread-count/', NotificationUnreadCountAPIView.as_view(), name='notification-unread-count'),
    path('notifications/<int:pk>/', NotificationDetailAPIView.as_view(), name='notification-detail'),
    path('notifications/<int:pk>/read/', NotificationReadAPIView.as_view(), name='notification-read'),
    path('notifications/read-all/', NotificationReadAllAPIView.as_view(), name='notification-read-all'),
    path('notifications/<int:pk>/acknowledge/', NotificationAcknowledgeAPIView.as_view(), name='notification-acknowledge'),
    path('shipments/<int:shipment_id>/events/', ShipmentEventListAPIView.as_view(), name='shipment-event-list'),
    path('events/<int:pk>/', EventDetailAPIView.as_view(), name='event-detail'),
    path('notification-preferences/', NotificationPreferenceAPIView.as_view(), name='notification-preferences'),

    # Phase 15: Operational Command Center, Alert Intelligence & Management Dashboard
    path('operations/dashboard/', OperationalDashboardAPIView.as_view(), name='operations-dashboard'),
    path('operations/health/', OperationalHealthAPIView.as_view(), name='operations-health'),
    path('operations/attention/', OperationalAttentionQueueAPIView.as_view(), name='operations-attention'),
    path('operations/alerts/', OperationalAlertIntelligenceAPIView.as_view(), name='operations-alerts'),
    path('operations/alerts/trends/', OperationalAlertTrendsAPIView.as_view(), name='operations-alerts-trends'),
    path('operations/risk-distribution/', OperationalRiskDistributionAPIView.as_view(), name='operations-risk-distribution'),
    path('operations/incidents/', OperationalIncidentIntelligenceAPIView.as_view(), name='operations-incidents'),
    path('operations/telemetry/', OperationalTelemetryIntelligenceAPIView.as_view(), name='operations-telemetry'),
    path('operations/market/', OperationalMarketIntelligenceAPIView.as_view(), name='operations-market'),
    path('operations/automation/', OperationalAutomationIntelligenceAPIView.as_view(), name='operations-automation'),
    path('operations/shipments/<int:shipment_id>/summary/', ShipmentOperationalSummaryAPIView.as_view(), name='operations-shipment-summary'),

    # Phase 16: Production Reliability, Observability & Resilience
    path('system/health/', HealthCheckAPIView.as_view(), name='system-health'),
    path('system/readiness/', ReadinessCheckAPIView.as_view(), name='system-readiness'),
    path('system/metrics/', SystemMetricsAPIView.as_view(), name='system-metrics'),
    path('system/status/', SystemStatusAPIView.as_view(), name='system-status'),

    # Phase 17: Analytics, Reporting & Business Intelligence
    path('analytics/dashboard/', AnalyticsDashboardAPIView.as_view(), name='analytics-dashboard'),
    path('analytics/shipments/', AnalyticsShipmentsAPIView.as_view(), name='analytics-shipments'),
    path('analytics/delivery-performance/', AnalyticsDeliveryPerformanceAPIView.as_view(), name='analytics-delivery-performance'),
    path('analytics/financial/', AnalyticsFinancialAPIView.as_view(), name='analytics-financial'),
    path('analytics/market/', AnalyticsMarketAPIView.as_view(), name='analytics-market'),
    path('analytics/risk/', AnalyticsRiskAPIView.as_view(), name='analytics-risk'),
    path('analytics/incidents/', AnalyticsIncidentAPIView.as_view(), name='analytics-incidents'),
    path('analytics/routes/', AnalyticsRouteAPIView.as_view(), name='analytics-routes'),
    path('analytics/automation/', AnalyticsAutomationAPIView.as_view(), name='analytics-automation'),
    path('analytics/events/', AnalyticsEventAPIView.as_view(), name='analytics-events'),
    path('analytics/corridors/', AnalyticsCorridorAPIView.as_view(), name='analytics-corridors'),
    path('analytics/top-performers/', AnalyticsTopPerformersAPIView.as_view(), name='analytics-top-performers'),
    path('analytics/trends/', AnalyticsTrendsAPIView.as_view(), name='analytics-trends'),
    path('analytics/reports/<str:report_type>/', AnalyticsReportsAPIView.as_view(), name='analytics-reports'),

    # Phase 18: External Integrations, Webhooks & Enterprise Data Exchange
    path('integrations/', ExternalIntegrationListCreateAPIView.as_view(), name='integration-list-create'),
    path('integrations/<int:pk>/', ExternalIntegrationDetailAPIView.as_view(), name='integration-detail'),
    path('integrations/<int:pk>/activate/', ExternalIntegrationActivateAPIView.as_view(), name='integration-activate'),
    path('integrations/<int:pk>/deactivate/', ExternalIntegrationDeactivateAPIView.as_view(), name='integration-deactivate'),
    path('integrations/<int:pk>/health/', ExternalIntegrationHealthAPIView.as_view(), name='integration-health'),
    path('integrations/<int:pk>/webhooks/', WebhookEndpointListCreateAPIView.as_view(), name='integration-webhook-list-create'),
    path('webhooks/<int:pk>/', WebhookEndpointDetailAPIView.as_view(), name='webhook-endpoint-detail'),
    path('webhooks/<int:pk>/activate/', WebhookEndpointActivateAPIView.as_view(), name='webhook-endpoint-activate'),
    path('webhooks/<int:pk>/deactivate/', WebhookEndpointDeactivateAPIView.as_view(), name='webhook-endpoint-deactivate'),
    path('webhooks/<int:pk>/rotate-secret/', WebhookEndpointRotateSecretAPIView.as_view(), name='webhook-endpoint-rotate-secret'),
    path('integrations/<int:pk>/deliveries/', IntegrationDeliveriesListAPIView.as_view(), name='integration-deliveries-list'),
    path('webhooks/<int:pk>/deliveries/', WebhookEndpointDeliveriesListAPIView.as_view(), name='webhook-endpoint-deliveries-list'),
    path('webhook-deliveries/<int:pk>/', WebhookDeliveryDetailAPIView.as_view(), name='webhook-delivery-detail'),
    path('webhook-deliveries/<int:pk>/retry/', WebhookDeliveryRetryAPIView.as_view(), name='webhook-delivery-retry'),
    path('integrations/events/publish/', IntegrationEventPublishAPIView.as_view(), name='integration-event-publish'),
    path('webhooks/inbound/<int:integration_id>/', InboundWebhookReceiverAPIView.as_view(), name='inbound-webhook-receiver'),

    # Phase 19: Advanced Security, Compliance & Governance
    path('security/overview/', SecurityOverviewAPIView.as_view(), name='security-overview'),
    path('security/events/', SecurityAuditEventListAPIView.as_view(), name='security-event-list'),
    path('security/events/<int:pk>/', SecurityAuditEventDetailAPIView.as_view(), name='security-event-detail'),
    path('security/incidents/', SecurityIncidentListAPIView.as_view(), name='security-incident-list'),
    path('security/incidents/<int:pk>/', SecurityIncidentDetailAPIView.as_view(), name='security-incident-detail'),
    path('security/incidents/<int:pk>/assign/', SecurityIncidentAssignAPIView.as_view(), name='security-incident-assign'),
    path('security/incidents/<int:pk>/resolve/', SecurityIncidentResolveAPIView.as_view(), name='security-incident-resolve'),
    path('security/incidents/<int:pk>/dismiss/', SecurityIncidentDismissAPIView.as_view(), name='security-incident-dismiss'),
    path('security/users/<int:pk>/history/', UserSecurityHistoryAPIView.as_view(), name='user-security-history'),
    path('security/policies/', SecurityPolicyListCreateAPIView.as_view(), name='security-policy-list-create'),
    path('security/policies/<int:pk>/', SecurityPolicyDetailAPIView.as_view(), name='security-policy-detail'),
    path('security/audit-integrity/', AuditIntegrityCheckAPIView.as_view(), name='security-audit-integrity'),
    path('security/reports/<str:report_type>/', SecurityComplianceReportAPIView.as_view(), name='security-compliance-reports'),

    # Ratings
    path('ratings/', RatingListCreateView.as_view(), name='rating-list-create'),
]





