# Generated by Django 5.2.17 on 2026-08-20 22:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_transporterverificationaudit"),
        ("marketplace", "0004_proofofdelivery_shipmentdocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreightInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="ETB", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INITIATED", "Payment Initiated"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Payment Succeeded"),
                            ("FAILED", "Payment Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payable_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="marketplace.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freight Invoice",
                "verbose_name_plural": "Freight Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreightSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_freight_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0500"), max_digits=5
                    ),
                ),
                (
                    "platform_commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "transporter_net_payable",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending e-POD"),
                            ("READY", "Ready for Payment"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAID", "Paid into Escrow State"),
                            ("SETTLED", "Fully Settled"),
                            ("DISPUTED", "Disputed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="marketplace.freightinvoice",
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="marketplace.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freight Settlement",
                "verbose_name_plural": "Freight Settlements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="ETB", max_length=10)),
                ("provider", models.CharField(default="MOCK", max_length=50)),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "payment_method",
                    models.CharField(default="MOCK_TRANSFER", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INITIATED", "Payment Initiated"),
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Payment Succeeded"),
                            ("FAILED", "Payment Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.freightsettlement",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="marketplace.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Dispute Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Dispute Resolved"),
                            ("REJECTED", "Dispute Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="marketplace.payment",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_raised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="marketplace.freightsettlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Dispute",
                "verbose_name_plural": "Payment Disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransporterPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "net_payout_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Settlement"),
                            ("SCHEDULED", "Payout Scheduled"),
                            ("PROCESSING", "Payout Processing"),
                            ("PAID", "Payout Transferred"),
                            ("FAILED", "Payout Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payout_reference", models.CharField(blank=True, max_length=100)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="marketplace.freightsettlement",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="accounts.transporterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporter Payout",
                "verbose_name_plural": "Transporter Payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
